version: 0.2

   env:  
     variables:  
       AWS\_ACCOUNT\_ID: "104780120723"  
       AWS\_DEFAULT\_REGION: us-east-1"  
       IMAGE\_REPO\_NAME: "my-webapp-repo-github"  
       ECS\_CLUSTER\_NAME: "my-cluster"  
       ECS\_SERVICE\_NAME: "my-webapp-task-service"  
       ECS\_TASK\_DEFINITION\_NAME: "my-webapp-task"

   phases:  
     pre\_build:  
       commands:  
         \- echo Logging in to Amazon ECR...  
         \- REPOSITORY\_URI=$AWS\_ACCOUNT\_ID.dkr.ecr.$AWS\_DEFAULT\_REGION.amazonaws.com/$IMAGE\_REPO\_NAME  
         \- aws ecr get-login-password \--region $AWS\_DEFAULT\_REGION | docker login \--username AWS \--password-stdin $REPOSITORY\_URI

     build:  
       commands:  
         \- echo Build started on \`date\`  
         \- COMMIT\_HASH=$(echo $CODEBUILD\_RESOLVED\_SOURCE\_VERSION | cut \-c 1-7)  
         \- IMAGE\_TAG=${COMMIT\_HASH:=latest}  
         \- echo Building the Docker image with tag $IMAGE\_TAG...  
         \- docker build \-t $REPOSITORY\_URI:$IMAGE\_TAG .  
         \- echo Pushing the Docker image...  
         \- docker push $REPOSITORY\_URI:$IMAGE\_TAG

     post\_build:  
       commands:  
         \- echo Build completed on \`date\`  
         \- echo Creating new task definition...  
         \- IMAGE\_URI\_WITH\_TAG=$REPOSITORY\_URI:$IMAGE\_TAG  
         \# taskdef.jsonのプレースホルダーを、ビルドした実際のイメージURIに置き換える  
         \- sed \-i \-e "s|\<IMAGE\_URI\_PLACEHOLDER\>|$IMAGE\_URI\_WITH\_TAG|g" taskdef.json  
         \# 新しいタスク定義を登録し、そのリビジョンを取得  
         \- NEW\_TASK\_INFO=$(aws ecs register-task-definition \--cli-input-json file://taskdef.json)  
         \- NEW\_REVISION=$(echo $NEW\_TASK\_INFO | jq .taskDefinition.revision)  
         \- echo "New task definition revision: $NEW\_REVISION"  
         \# ECSサービスを更新して、新しいタスク定義を適用  
         \- echo "Updating ECS service..."  
         \- aws ecs update-service \--cluster $ECS\_CLUSTER\_NAME \--service $ECS\_SERVICE\_NAME \--task-definition "$ECS\_TASK\_DEFINITION\_NAME:$NEW\_REVISION" \--force-new-deployment  
         \- echo "ECS service updated successfully."
